main = ".open-next/worker.js"
name = "anki-interview-app"
compatibility_date = "2025-03-25"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"


[vars]
SESSION_MAX_AGE = "604800"
SESSION_COOKIE_NAME = "anki_session"
NEXT_PUBLIC_BACKEND_URL= "https://anki-interview-app.tomoima525.workers.dev"

