main = ".open-next/worker.js"
name = "anki-interview-app"
compatibility_date = "2025-09-15"
compatibility_flags = ["nodejs_compat","enable_nodejs_process_v2"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"


[vars]
ENVIRONMENT = "production"
SESSION_MAX_AGE = "604800"
SESSION_COOKIE_NAME = "anki_session"
NEXT_PUBLIC_BACKEND_URL= "https://anki-interview-app.tomoima525.workers.dev"
NEXT_PUBLIC_GOOGLE_CLIENT_ID="494913230082-44coq05pq6cn0hs5sdshkksm48lbqtjb.apps.googleusercontent.com"
GOOGLE_CLIENT_ID="494913230082-44coq05pq6cn0hs5sdshkksm48lbqtjb.apps.googleusercontent.com"

[observability]
[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = true